name: rocket
version: 0.1.3
description: Rocket is a parsing framework for parsing using efficient parsing algorithms
homepage: https://github.com/mezoni/rocket
environment:
  sdk: '>=2.13.0 < 3.0.0'
dev_dependencies:
  charcode: ^1.2.0
  lints: ^1.0.1
  stack_trace: ^1.10.0
  test: ^1.17.3
