name: rocket
version: 0.1.10
description: Rocket is a parsing framework for parsing any kind (text, binary etc) of data structures using efficient parsing algorithms.
homepage: https://github.com/mezoni/rocket
environment:
  sdk: '>=2.13.0 < 3.0.0'
dependencies:
  meta: ^1.4.0
  source_span: ^1.8.1
dev_dependencies:
  charcode: ^1.2.0
  lints: ^1.0.1  
  test: ^1.17.3
